export default {
  "id": "Tn6-PIqc4UM",
  "title": "React in 100 Seconds",
  "lengthSeconds": "128",
  "keywords": [
    "webdev",
    "app development",
    "lesson",
    "tutorial",
    "js",
    "react",
    "react js",
    "react native",
    "react tutorial",
    "react hooks",
    "javascript"
  ],
  "channelTitle": "Fireship",
  "channelId": "UCsBjURrPoezykLs9EqgamOA",
  "thumbnail": [
    {
      "url": "https://i.ytimg.com/vi/Tn6-PIqc4UM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCbsdXCA2CD45TCj6o9sjYRrIx2lA",
      "width": 168,
      "height": 94
    },
    {
      "url": "https://i.ytimg.com/vi/Tn6-PIqc4UM/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLACcLTOppKnz9b1QDag1o_LhOC6yg",
      "width": 196,
      "height": 110
    },
    {
      "url": "https://i.ytimg.com/vi/Tn6-PIqc4UM/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCPBUoCd8ySiHiUEIEhwuu_i1C4Mg",
      "width": 246,
      "height": 138
    },
    {
      "url": "https://i.ytimg.com/vi/Tn6-PIqc4UM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA05Vui5cyzPZPouziZNcg4rnxtcw",
      "width": 336,
      "height": 188
    },
    {
      "url": "https://i.ytimg.com/vi_webp/Tn6-PIqc4UM/maxresdefault.webp",
      "width": 1920,
      "height": 1080
    }
  ],
  "allowRatings": true,
  "viewCount": "822666",
  "isPrivate": false,
  "isUnpluggedCorpus": false,
  "isLiveContent": false,
  "isCrawlable": true,
  "isFamilySafe": true,
  "availableCountries": [
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BL",
    "BM",
    "BN",
    "BO",
    "BQ",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CU",
    "CV",
    "CW",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "EH",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IO",
    "IQ",
    "IR",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KP",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MF",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SD",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "SS",
    "ST",
    "SV",
    "SX",
    "SY",
    "SZ",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW"
  ],
  "isUnlisted": false,
  "category": "Science & Technology",
  "publishDate": "2020-09-08",
  "uploadDate": "2020-09-08",
  "storyboards": "https://i.ytimg.com/sb/Tn6-PIqc4UM/storyboard3_L$L/$N.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgiQkJuPBg==|48#27#100#10#10#0#default#rs$AOn4CLDCxWRqhLE6Iy4Rp3pUbjvvEnoOqg|80#45#65#10#10#2000#M$M#rs$AOn4CLDxN2-bqYjep47mJ7QENy502jomTQ|160#90#65#5#5#2000#M$M#rs$AOn4CLBduow2smfIT0MdXNhk6JSmvICaMA"
}